---
workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - if: $CI_COMMIT_BRANCH == 'coreweave'
      when: always

default:
  tags:
    - ord1-tenant

Helm lint:
  stage: test
  allow_failure: true
  image:
    name: alpine/helm:3.12.1
    entrypoint: [""]
  script:
    - cd charts/authentik
    - helm dep update
    - helm lint .
  needs: []

Helm push:
  stage: deploy
  only:
    refs:
      - coreweave
    changes:
      - charts/**/*
  image:
    name: alpine/helm:3.12.1
    entrypoint: [""]
  script:
    - apk add git
    - helm plugin install https://github.com/chartmuseum/helm-push.git
    - cd charts
    - helm repo add helm_repo $HELM_REPO_URL --username $HELM_REPO_USER --password $HELM_REPO_PASS
    - helm repo add authentik https://charts.goauthentik.io && helm repo update
    - for x in $(find . -maxdepth 1 -mindepth 1 -type d -not -path "./authentik"); do helm package $x --destination ./authentik/charts; done
    - helm cm-push ./authentik helm_repo -f
  needs:
    - Helm lint
