{{- if .Values.ingress.enabled -}}
  {{- $apiIsStable := include "authentik.capabilities.ingress.isStable" . -}}
apiVersion: {{ include "authentik.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "authentik.names.fullname" . }}
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.ingress.annotations }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}
{{ include "coreweave.ingressAnnotations" . | indent 2 }}
  {{- end }}
spec:
  {{- if and $apiIsStable .Values.ingress.ingressClassName }}
  ingressClassName: {{ $.Values.ingress.ingressClassName }}
  {{- end }}
  tls:
  {{- if .Values.ingress.tls }}
  {{- with .Values.ingress.tls }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- else }}
    - hosts:
      - {{ include "coreweave.externalDnsName" . }}
      secretName: {{ include "coreweave.certSecretName" . }}
  {{- end }}
  rules:
    {{- if .Values.ingress.hosts }}
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path | quote }}
            {{- if $apiIsStable }}
            pathType: {{ default "Prefix" .pathType }}
            {{- end }}
            backend:
              {{- if $apiIsStable }}
              service:
                name: {{ include "authentik.names.fullname" $ }}
                port:
                  name: {{ $.Values.service.name }}
              {{- else }}
              serviceName: {{ include "authentik.names.fullname" $ }}
              servicePort: {{ $.Values.service.port }}
              {{- end }}
          {{- end }}
    {{- end }}
    {{- else }}
    - host: {{ include "coreweave.externalDnsName" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "authentik.names.fullname" $ }}
                port:
                  name: {{ $.Values.service.name }}
    {{- end }}
{{- end }}
