{{- if .Values.ingress.enabled -}}
  {{- $apiIsStable := include "authentik.capabilities.ingress.isStable" . -}}
apiVersion: {{ include "authentik.capabilities.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ include "authentik.names.fullname" . }}
  labels:
    {{- include "authentik.labels" . | nindent 4 }}
    {{- with .Values.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{ include "coreweave.ingressAnnotations" . | indent 2 }}
spec:
  {{- if and $apiIsStable .Values.ingress.ingressClassName }}
  ingressClassName: {{ $.Values.ingress.ingressClassName }}
  {{- end }}
  tls:
    - hosts:
      - {{ include "coreweave.externalDnsName" . }}
      secretName: {{ include "coreweave.certSecretName" . }}
  rules:
    - host: {{ include "coreweave.externalDnsName" . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "authentik.names.fullname" $ }}
                port:
                  name: {{ $.Values.service.name }}
{{- end }}
