apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app.kubernetes.io/instance: {{.Release.Name}}
    app.kubernetes.io/name: postgresql
    role: primary
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  name: data-{{.Release.Name}}-postgresql-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ default "8Gi" (((.Values.postgresql).primary).persistence).requests }}
  {{- if (((.Values.postgresql).primary).persistence).storageClass }}
  storageClassName: {{ (((.Values.postgresql).primary).persistence).storageClass }}
  {{- else }}
  storageClassName: block-nvme-{{default "ord1" (.Values).region | lower}}
  {{- end }}
  volumeMode: Filesystem
