apiVersion: v1
immutable: true
kind: Secret
metadata:
  name: {{ .Release.Name }}-keys
  labels:
    {{- include "authentik.labels" $ | nindent 4 }}
type: Opaque
data:
  secret_key: {{ randAlphaNum 49 | b64enc }}
  akadmin_password: {{ randAlphaNum 16 | b64enc }}
  ldapsvc_password: {{ randAlphaNum 16 | b64enc }}
  bootstrap_token: {{ randAlphaNum 32 | b64enc }}
  admin_email: {{ (default "foo@bar.com" .Values.adminEmail ) | b64enc }}
