apiVersion: v1
data:
  okta-ldap-mapping-blueprint.yaml: |
    # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
    context: {}
    version: 1
    metadata:
      labels:
        blueprints.goauthentik.io/instantiate: "{{ empty ((.Values.customBlueprints).federation).ldap | not }}"
      name: Custom Blueprints - Okta LDAP Mappings
    entries:
      - identifiers:
          managed: goauthentik.io/sources/ldap/okta-user
        model: authentik_sources_ldap.ldapsourcepropertymapping
        attrs:
          name: "Okta LDAP: User Mapping Properties"
          expression: |
            return {
              "attributes": {
                "googleUid": ldap.get("googleUid"),
                "givenName": list_flatten(ldap.get('givenName')),
                "sn": list_flatten(ldap.get('sn')),
                "dispalyName": ldap.get('cn'),
                "description": ldap.get("description"),
                "uniqueMember": ldap.get("uniqueMember"),

              },
              "username": ldap.get("uid"),
              "name": ldap.get("cn"),
              "email": ldap.get("mail"),
            }

      - identifiers:
          managed: goauthentik.io/sources/ldap/okta-group
        model: authentik_sources_ldap.ldapsourcepropertymapping
        attrs:
          name: "Okta LDAP: Group Mapping Properties"
          expression: |
            return {
              "attributes": {
                "description": ldap.get("description"),

              },
              "name": ldap.get("cn"),
            }

kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-okta-ldap-mapping-blueprint
  labels:
    {{- include "authentik.labels" (dict "context" . "component" .Values.server.name) | nindent 4 }}
