apiVersion: v1
data:
  google-ldap-mapping-blueprint.yaml: |
    # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
    context: {}
    version: 1
    metadata:
      labels:
        blueprints.goauthentik.io/instantiate: "{{ empty ((.Values.customBlueprints).federation).ldap | not }}"
      name: Custom Blueprints - Google Secure LDAP Mappings
    entries:
      - identifiers:
          managed: goauthentik.io/sources/ldap/google-user
        model: authentik_sources_ldap.ldapsourcepropertymapping
        attrs:
          name: "Google Secure LDAP Mapping: User Mapping Properties"
          expression: |
            return {
              "attributes": {
                "googleUid": ldap.get("googleUid"),
                "posixUid": ldap.get("posixUid"),
                "sn": list_flatten(ldap.get("sn")),
                "givenName": list_flatten(ldap.get("givenName")),
                "displayName": ldap.get("displayName"),
                "title": ldap.get("title"),
                "employeeNumber": ldap.get("employeeNumber"),
                "employeeType": ldap.get("employeeType"),
                "departmentNumber": ldap.get("departmentNumber"),
                "physicalDeliveryOfficeName": ldap.get("physicalDeliveryOfficeName"),
                "jpegPhoto": ldap.get("jpegPhoto"),
                "entryUuid": list_flatten(ldap.get("entryUuid")),
                "objectSid": ldap.get("objectSid"),
                "uidNumber": ldap.get("uidNumber"),
                "gidNumber": ldap.get("gidNumber"),
                "homeDirectoy": ldap.get("homeDirectory"),
                "loginShell": ldap.get("loginShell"),
                "gecos": ldap.get("gecos"),
                "sshPublicKey": ldap.get("sshPublicKey"),
              },
              "username": ldap.get("uid"),
              "name": ldap.get("cn"),
              "email": ldap.get("mail"),
            }
      - identifiers:
          managed: goauthentik.io/sources/ldap/google-group
        model: authentik_sources_ldap.ldapsourcepropertymapping
        attrs:
          name: "Google Secure LDAP Mapping: Group Mapping Properties"
          expression: |
            return {
              "attributes": {
                "displayName": ldap.get("displayName"),
                "description": ldap.get("description"),
                "gidNumber": ldap.get("gidNumber"),
                "entryUuid": ldap.get("entryUuid"),
                "objectSid": ldap.get("objectSid"),
                "googleAdminCreated": ldap.get("googleAdminCreated"),
              },
              "name": ldap.get("cn"),
            }


kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-google-ldap-mapping-blueprint
  labels:
    {{- include "authentik.labels" (dict "context" . "component" .Values.server.name) | nindent 4 }}
