apiVersion: v1
data:
  users-passwords-blueprint.yaml: |
    # yaml-language-server: $schema=https://goauthentik.io/blueprints/schema.json
    context: {}
    metadata:
      labels:
        blueprints.goauthentik.io/instantiate: "{{ empty ((.Values).customBlueprints).users | not }}"
      name: Custom Blueprints - User Passwords
    version: 1
    entries:
    - model: authentik_blueprints.metaapplyblueprint
      attrs:
        identifiers:
          name: Default - Password change flow
        required: false
    {{- range ((.Values).customBlueprints).users }}
    - attrs:
        name: {{ .name }}
        path: {{ default "users" .path }}
        username: {{ .userName }}
        password: !Env [{{ printf "%s_password" .userName }}, changeme]
      conditions: []
      id: {{ .userName }}
      identifiers:
        name: {{ .name }}
      model: authentik_core.user
      state: {{ default "created" .passwordState }}
    {{- end }}
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-users-passwords-blueprint
  labels:
    {{- include "authentik.labels" $ | nindent 4 }}
